In [ ]:
#1
import numpy as np

A = np.matrix("2,3,1;-1,1,0;1,2,-1")
B = np.matrix("1,2,1;0,1,2;3,1,1")

AB = np.dot(A,B)
BA = np.dot(B,A)
C = AB - BA
print("A = \n", A)
print("B = \n", B)
print("A * B = \n", AB)
print("B * A = \n", BA)
print("C = AB - BA = \n", C)


A = 
 [[ 2  3  1]
 [-1  1  0]
 [ 1  2 -1]]
B = 
 [[1 2 1]
 [0 1 2]
 [3 1 1]]
A * B = 
 [[ 5  8  9]
 [-1 -1  1]
 [-2  3  4]]
B * A = 
 [[ 1  7  0]
 [ 1  5 -2]
 [ 6 12  2]]
C = AB - BA = 
 [[ 4  1  9]
 [-2 -6  3]
 [-8 -9  2]]


In [ ]:
#2
import numpy as np

matrix = np.matrix("-1,0,2;0,1,0;1,2,-1")
result = np.linalg.matrix_power(matrix,2)

print("Our matrix = \n", matrix)
print("Out result power 2 = \n", result)

Our matrix = 
 [[-1  0  2]
 [ 0  1  0]
 [ 1  2 -1]]
Out result power 2 = 
 [[ 3  4 -4]
 [ 0  1  0]
 [-2  0  3]]


In [ ]:
#3
import numpy as np

a = np.matrix("5,8,-4;6,9,-5;4,7,-3")
b = np.matrix("3,2,5;4,-1,3;9,6,5")

AB = np.dot(a, b)

print("Matrix a = \n", a)
print("Matrix b = \n", b)
print("Our result multiple matrix a in b = \n", AB)

Matrix a = 
 [[ 5  8 -4]
 [ 6  9 -5]
 [ 4  7 -3]]
Matrix b = 
 [[ 3  2  5]
 [ 4 -1  3]
 [ 9  6  5]]
Our result multiple matrix a in b = 
 [[ 11 -22  29]
 [  9 -27  32]
 [ 13 -17  26]]


In [ ]:
#4
import numpy as np

matrix = np.matrix("0,2,0;3,4,5;6,7,8")
result = np.linalg.det(matrix)

print("Our matrix = \n", matrix)
print("Our result det(matrix) = ", result)

Our matrix = 
 [[0 2 0]
 [3 4 5]
 [6 7 8]]
Our result det(matrix) =  12.0


In [ ]:
#5
import numpy as np

matrix = np.matrix("2,3,4,1;1,2,3,4;3,4,1,2;4,1,2,3")
result = np.linalg.det(matrix)

print("Our matrix = \n", matrix)
print("Our result det(matrix) = ", result.round(3))

Our matrix = 
 [[2 3 4 1]
 [1 2 3 4]
 [3 4 1 2]
 [4 1 2 3]]
Our result det(matrix) =  -160.0


In [ ]:
#6
import numpy as np

matrix = np.matrix("2,5,7;6,3,4;5,-2,-3")
result = np.linalg.inv(matrix)

print("Our matrix = \n", matrix)
print("Our result inverted matrix = \n", result)


Our matrix = 
 [[ 2  5  7]
 [ 6  3  4]
 [ 5 -2 -3]]
Our result inverted matrix = 
 [[  1.  -1.   1.]
 [-38.  41. -34.]
 [ 27. -29.  24.]]


In [ ]:
#7
import numpy as np

matrix = np.matrix("1,-1,3,4;0,-1,2,1;1,1,-1,2;2,3,-5,3")
result = np.linalg.matrix_rank(matrix)

print("Our matrix = \n", matrix)
print("Our result rank matrix = ", result)


Our matrix = 
 [[ 1 -1  3  4]
 [ 0 -1  2  1]
 [ 1  1 -1  2]
 [ 2  3 -5  3]]
Our result rank matrix =  3


In [3]:
#8
import numpy as np

a = np.matrix("14,4,6;5,-3,2;10,-11,5")
b = np.matrix("30;15;36")

def metod_сram(a,b):
  det_a = np.linalg.det(a)
  x = []
  if det_a != 0:
    for i in range(len(b)):
      Ai = a.copy()
      Ai[:, i] = b

      det_Ai = np.linalg.det(Ai)

      xi = det_Ai / det_a
      x.append(xi.round(3))
  return x
def matrix_metod(a,b):
  a_inv = np.linalg.inv(a)

  x = np.dot(a_inv,b)
  return x
result_matrix_metod = matrix_metod(a,b)
result_metod_cram = metod_сram(a, b)
print("Our matrix a = \n", a)
print("Our matrix b = \n", b)
print("Result Metod Crama = ", result_metod_cram)
print("Result Matrix Metod = ", result_matrix_metod)
print("Result by the agency solve()\n", np.linalg.solve(a,b).round(3))

Our matrix a = 
 [[ 14   4   6]
 [  5  -3   2]
 [ 10 -11   5]]
Our matrix b = 
 [[30]
 [15]
 [36]]
Result Metod Crama =  [2.0, -1.0, 1.0]
Result Matrix Metod =  [[ 2.]
 [-1.]
 [ 1.]]
Result by the agency solve()
 [[ 2.]
 [-1.]
 [ 1.]]


In [ ]:
#2
#5. Створіть прямокутну матрицю A, яка має N рядків і M стовпців з випадковими елементами. Знайдіть суму елементів всієї матриці. Визначте, яку долю в цій сумі складає сума елементів кожного рядка.
import numpy as np

N = int(input("N = "))
M = int(input("M = "))

random_matrix = np.random.randint(0, 101, size=(N, M))
result = 0

for i in random_matrix:
   for j in i:
      result += j

sum_row = np.sum(random_matrix, axis = 1)
count = 1

for i in sum_row:
   print(f"Row number {count} = ", i)
   count += 1

print("Our result = ", result)
print("Our matrix = \n", random_matrix)


N = 3
M = 3
Row number 1 =  167
Row number 2 =  166
Row number 3 =  141
Our result =  474
Our matrix = 
 [[31 44 92]
 [ 7 70 89]
 [88  2 51]]
